#compiling for pocketbook emulator

PATH=$(POCKETBOOKSDK)\bin

CC = $(POCKETBOOKSDK)\bin\gcc
CPP= $(POCKETBOOKSDK)\bin\g++

OBJPATH=obj/pbemu

INCLUDE=

LIBS=-linkview -lfreetype -ljpeg -lz -lgdi32
CFLAGS=-static -Wall -O2 -fomit-frame-pointer  -DARCH_PBEMU
SQLITEFLAGS= 


include makefiles/makefile.inkview

