#compiling for OpenInkpot emulator

CC = gcc
CPP = g++

LIBS= -lecore -ledje -lecore_evas
INCLUDE = -I/usr/include/eina-0/ -I/usr/include/eina-0/eina -I/usr/include/efreet -I/usr/include/ewl
CFLAGS=-DARCH_OI

OBJPATH=obj/oi


include makefiles/makefile.oi.commons