#compiling for pocketbook arm arch

CC = gcc
CPP = g++

LIBS= -lecore -ledje -lecore_evas
INCLUDE = -I/usr/include/eina-0/ -I/usr/include/eina-0/eina -I/usr/include/efreet
CFLAGS=-DARCH_OI
SQLITEFLAGS= -DSQLITE_MIXED_ENDIAN_64BIT_FLOAT 

OBJPATH=obj/oi

SOURCES = src/include/GUI/efl/test.cpp
OBJECTS = 


mindcraft: $(OBJECTS) $(SOURCES)
	$(CPP) $(CFLAGS) $(INCLUDE) -o $@ $(SOURCES) $(OBJECTS) $(LIBS) 




	
	