#compiling for pocketbook emulator

POCKETBOOKSDK = ~/opt/PBSDK/arm-linux

PATH=~/opt/PBSDK/arm-linux

CC = $(POCKETBOOKSDK)/bin/gcc
CPP= $(POCKETBOOKSDK)/bin/g++


#CC = gcc
#CPP = g++
OBJPATH=obj/pbemu

INCLUDE=

LIBS=-linkview -lfreetype -ljpeg -lz -lgdi32 -lcurl
CFLAGS=-static -Wall -O2 -fomit-frame-pointer  -DARCH_PBEMU
SQLITEFLAGS= 


include makefiles/makefile.inkview

